USE FINAL;

CREATE TABLE SUCURSAL(
ID_SUCURSAL INT IDENTITY(1,1) PRIMARY KEY,
DISTRITO VARCHAR(30),
CALLE VARCHAR (30),
NUMERO INT 
)

CREATE TABLE PERSONA(
DNI_PERSONA INT PRIMARY KEY,
NOMBRES VARCHAR(50),
APELLIDOS VARCHAR(50),
ID_SUCURSAL INT, 
FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
)

CREATE TABLE CLIENTE(
DNI_CLIENTE INT PRIMARY KEY
FOREIGN KEY (DNI_CLIENTE) REFERENCES PERSONA(DNI_PERSONA)
)

CREATE TABLE EMPLEADO(
DNI_EMPLEADO INT PRIMARY KEY,
HORA_ENTRADA TIME,
HORA_SALIDA TIME,
SUELDO SMALLMONEY,
FOREIGN KEY (DNI_EMPLEADO) REFERENCES PERSONA(DNI_PERSONA)
)

CREATE TABLE CAJERO(
DNI_CAJERO INT PRIMARY KEY,
FOREIGN KEY (DNI_CAJERO) REFERENCES EMPLEADO(DNI_EMPLEADO)
)
CREATE TABLE VENDEDOR(
DNI_VENDEDOR INT PRIMARY KEY,
FOREIGN KEY (DNI_VENDEDOR) REFERENCES EMPLEADO(DNI_EMPLEADO)
)

CREATE TABLE FACTURA(
CODIGO_FACTURA INT PRIMARY KEY,
FECHA_HORA DATETIME,
DNI_CAJERO INT
)

CREATE TABLE VENTA(
ID_VENTA INT PRIMARY KEY,
FECHA_HORA DATETIME,
TOTAL INT,
CODIGO_FACTURA INT,
DNI_VENDEDOR INT,
DNI_CLIENTE INT,
FOREIGN KEY (CODIGO_FACTURA) REFERENCES FACTURA(CODIGO_FACTURA),
FOREIGN KEY (DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR),
FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
)
CREATE TABLE PRODUCTO(
CODIGO_PRODUCTO INT PRIMARY KEY,
NOMBRE VARCHAR(50),
MARCA VARCHAR (50),
CATEGORIA VARCHAR (50),
STOCK INT,
PRECIO SMALLMONEY
)
CREATE TABLE VENTA_PRODUCTO(
ID_VENTA INT ,
CODIGO_PRODUCTO INT ,
CANTIDAD INT,
PRIMARY KEY (ID_VENTA,CODIGO_PRODUCTO),
FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA),
FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
)


CREATE TABLE RESERVA(
ID_RESERVA INT PRIMARY KEY,
DNI_CLIENTE INT,
FECHA_INICIO DATE,
FECHA_LIMITE DATE,
FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
)

CREATE TABLE RESERVA_PRODUCTO(
ID_RESERVA INT,
CODIGO_PRODUCTO INT,
CANTIDAD INT,
PRIMARY KEY (ID_RESERVA,CODIGO_PRODUCTO),
FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
)


CREATE TABLE VALE(
ID_VALE INT PRIMARY KEY,
DNI_EMPLEADO INT,
MONTO SMALLMONEY,
FECHA_EMISION DATE,
FECHA_VENCIMIENTO DATE,
FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)
)